config/routes.rb
Rails.application.routes.draw do
  get 'user/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'

  get 'signup' => 'user#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails tutorial</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path%></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstotorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="nav navbar-fixed-top navbar-inverse">
  <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "help", help_path %></li>
          <li><%= link_to "Log in", "#" %></li>
        </ul>
      </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Sample App Home </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | Sample App Home </title>
  </head>
  <body>
    <h1>About</h1>
    <p>Get the information about the Ruby on Rails Tutorial at the <a href="http/www.railstutorial.org/#help">Ruby on Rails help Tutorial</a> Sample application</p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | Sample App Home </title>
  </head>
  <body>
    <h1>Contact</h1>
    <p>Get the information about the Ruby on Rails Tutorial at the <a href="http/www.railstutorial.org/#contact">Ruby on Rails help Tutorial</a> Sample application</p>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | Sample App Home </title>
  </head>
  <body>
    <h1>Help</h1>
    <p>Get help on the Ruby on Rails Tutorial at the <a href="http/www.railstutorial.org/#help">Ruby on Rails help Tutorial</a> Sample application</p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%= yield(:title) %> | Sample App Home </title>
  </head>
  <body>
  <div class="center jumbotron">
    <h1>Welcome to the sample</h1>

    <h2>
      This is the hom page for the
      <a href="http://www.railstutorial.ro/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>

    <%= link_to "Sign up now!", signup_path, class: "btn btnlg btn-primary" %>
  </div>

  <%= link_to image_tag("rails.png", alt:"Rails logo"), 'http://rubyonrails.org' %>
  </body>
</html>

app/views/user/new.html.erb
<% provide(:title, "Sign Up") %>
<h1>Sing Up</h1>
<p>This will be a signup page.</p>